python led_cube.py -f ../../DotMatrixJava/examples/0000.dat -d 25
#python led_cube.py -f ../../DotMatrixJava/examples/0001.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0002.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0003.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0004.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0005.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0006.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0007.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0008.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0009.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0010.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0011.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0012.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0013.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0014.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0015.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0016.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0017.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0018.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0019.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0020.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0021.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0022.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0023.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0024.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0025.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0026.dat -d 25
python led_cube.py -f ../../DotMatrixJava/examples/0027.dat -d 25
